title: Qc_1st-principle_u_need_2_know
description: another self-established platform for sharing knowledge about quantum chemistry, first-principles and simulation techniques.
remote_theme: pages-themes/cayman@v0.2.0
markdown: Kramdown
plugins:
- jekyll-remote-theme
# website structure related

collections:
  categories:
    output: true

# 这里是为了设置layout，即文档模板的默认值，每一个scope对应一个value，value给定_layouts中一种模板。
defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
