theme: jekyll-theme-cayman
title: Qc_1st-principle_u_need_2_know
description: another self-established platform for sharing knowledge about quantum chemistry, first-principles and simulation techniques.