theme: jekyll-theme-cayman
markdown: Kramdown
title: QCet1stPrincpleUneed2know
description: sharing basic knowledge of quantum chemistry and first principle, also relevant simulation techniques.
# website structure related

collections:
  categories:
    output: true

# 这里是为了设置layout，即文档模板的默认值，每一个scope对应一个value，value给定_layouts中一种模板。
defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
